config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  # resources :users
  resources :woofs
  get '/login' => 'sessions#new' # sign in form
  post '/login' => 'sessions#create' # sign in action
  delete '/logout' => 'sessions#destroy' # sign out
  get '/contact' => 'pages#contact'
  get  '/about' => 'pages#about'

  resources :users do
   member do
     get :following, :followers
   end
 end

 resources :relationships
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="woofs">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(@current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary btn-small" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless @current_user == @user %>
  <div id="follow_form">
  <% if @current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= @current_user %>
<div class="stats">
  <div id="woof-stats" class="stat">
  <a href="#woofs-feed">
    <strong >
      <%= @user.woofs.count %>
    </strong><BR/>
    woofs
  </a>
  </div>
  <div id="following-stats" class="stat">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong><BR/>
    following
  </a>
  </div>
  <div id="followers-stats" class="stat">
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong><BR/>
      followers
    </a>
  </div>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(@current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-secondary btn-small" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= @current_user.name %></h1>
<div class="circle-img">
  <%= image_tag @woof.user.image, :alt => @woof.user.name%>
</div>



<section class="stats">

</section>

<span id="view-profile-links"><%= link_to "view my profile", @current_user %> | <%= link_to "edit my profile", edit_user_path(@current_user) %></span>

app/views/shared/_woof_form.html.erb
<%= form_for(@woof) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :status, placeholder: "What's woofin'? (max 300 characters)" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>