config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  # resources :users
  resources :woofs
  get '/login' => 'sessions#new' # sign in form
  post '/login' => 'sessions#create' # sign in action
  delete '/logout' => 'sessions#destroy' # sign out
  get '/contact' => 'pages#contact'
  get  '/about' => 'pages#about'

  resources :users do
   member do
     get :following, :followers
   end
 end

 resources :relationships
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    'Project 1' for <a href="http://www.generalassemb.ly" target="_blank">General Assembly</a> Sydney's Web Development Immersive 26 - by <a href="http://www.taryn.codes" target="_blank">Taryn Ewens.</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   "https://github.com/tarynelise/project1", target: "_blank" %></li>
      <li><%= link_to "Contact", "http://www.taryn.codes", target: "_blank" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "WOOFER", root_path, id: "logo" %>
    <%= image_tag "woofer-logo.png", id: "woofer-logo" %>
    <nav id="header-nav">
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? && @current_user.name.present? %>

          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', user_path(@current_user)%></li>
              <li><%= link_to "Settings", edit_user_path(@current_user) %></li>
              <li><%= link_to "Sign out #{ @current_user.name }", logout_path, :method => 'delete'%></li>
            </ul>

            <% elsif logged_in? && @current_user.name.nil? %>
            <li><%= link_to "Settings", edit_user_path(@current_user) %></li>

            <% else %>
              <li><%= link_to 'Sign up', new_user_path %></li>
              <li><%= link_to 'Sign in', login_path %></li>
      </ul>

      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-inner">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    </div>

          <%= yield %>
          <%= render 'layouts/footer' %>


  </body>
</html>